### ISSUE TITLE
generate build provider support for codeship

### ISSUE THREAD

**Issue by jritsema** [turnerlabs/harbor-compose#101]
UX could be...

```
$ hc generate my-app dev --build-provider codeship

done

Now you just need to:
- add your docker registry credentials to codeship.env
- download your AES key from your codeship project
- encrypt your codeship.env by running `jet encrypt codeship.env codeship.env.encrypted`
```

and the tool would output the following files...

- codeship-services.yml
- codeship-steps.yml
- .cicd/docker-compose.yml
- .cicd/harbor-compose.yml
- .cicd/codeship.env
- .cicd/version.sh (until they fix bug)
- .cicd/docker-push (until they fix bug)

...and add .cicd/codeship.env to .gitignore

**Comment by jritsema** [comment]
I was able to get this setup working...

- codeship-services.yml
- codeship-steps.yml
- .codeship
  - docker-compose.yml
  - harbor-compose.yml
  - codeship.env
  - version.sh
  - docker-push.sh

codeship-services.yml
```yaml
cicd:  
  image: quay.io/turner/harbor-cicd-image:v0.11.0
  encrypted_env_file: .codeship/codeship.env.encrypted
  add_docker: true
  volumes:
    - ./:/app
```

codeship-steps.yml
```yaml
- service: cicd
  name: set version
  command: sh .codeship/version.sh

- service: cicd
  name: build image
  command: docker-compose -f .codeship/docker-compose.yml build

- service: cicd
  name: push image
  command: sh .codeship/docker-push.sh

- service: cicd
  name: catalog image in harbor
  command: harbor-compose -f .codeship/docker-compose.yml -c .codeship/harbor-compose.yml catalog

- service: cicd
  tag: develop
  name: deploy image to harbor  (develop only)
  command: harbor-compose -f .codeship/docker-compose.yml -c .codeship/harbor-compose.yml deploy
```
