### ISSUE TITLE
Support for healthcheck_interval

### ISSUE THREAD

**Issue by jritsema** [turnerlabs/harbor-compose#129]
Support for [healthcheck_interval](https://github.com/turnerlabs/shipit-api/pull/35) in harbor-compose which includes:

- `up` command updating value if it's specified in harbor-compose.yml
- `generate` command writing current value to harbor-compose.yml
- `init` command prompting for value

```
version: "1"
shipments:
  my-web-app:
    env: dev
    barge: digital-sandbox
    enableMonitoring: false
    healthcheckIntervalSeconds: 10
```
