### ISSUE TITLE
Support 'discover' environment variables

### ISSUE THREAD

**Issue by jritsema** [turnerlabs/harbor-compose#132]
Model after `hidden` environment variables...

```
version: '2'
services:
  web:
    image: registry.services.dmtio.net/web:1.0.0
    ports:
    - 80:5000
    env_file: 
    - discover.env
```
