### ISSUE TITLE
Add support for hidden environment variables

### ISSUE THREAD

**Issue by jritsema** [turnerlabs/harbor-compose#19]
I'm thinking that, say you have a `docker-compose.yml` like this...

```
version: '2'
services:
  web:
    image: registry.services.dmtio.net/web:1.0.0
    ports:
     - "80:5000"
    env_file: hidden.env
```

...then you could store your secrets in `hidden.env` and exclude it from source control and then `harbor-compose up` could push these up to Harbor as hidden env vars.  Doesn't work so great for teams, but if you need to keep secrets...

Thoughts?

**Comment by wilsonodk** [comment]
Is there magic in the name `hidden.env` or is that just illustrative?

**Comment by jkurz** [comment]
So I think that for simplicity purposes, we should punt on integrating hidden envVars into harbor-compose for now. We need a way to declare hiddenEnvVars in the yaml, which means we will need to implement this into harbor-compose, not overload functionality in docker-compose. 

Because of this, I would like to focus on the `up` command. Get our minds around how we want to do that, and then integrate hidden env vars. I think we need a solid Harbor Compose API yml file declaration before we can discuss what this implementation will look like.

**Comment by jritsema** [comment]
Agreed.  And I'm thinking that we should look at a managed vault type service which might be an overall better solution for managing secrets rather than using env vars.

**Comment by jc-money** [comment]
For me, instead of a per-variable flag, I'd prefer a flag at the shipment level that would make all env vars hidden.

**Comment by wilsonodk** [comment]
@jc-money Wouldn't this mean that your values would be exposed and committed in the source repo?

**Comment by jc-money** [comment]
No - I am assuming that harbor-compose will handle env vars like [docker-compose](https://docs.docker.com/compose/environment-variables/). So the compose file will have place holders - then when "up" is run the env vars that exist locally will be used (and passed to Harbor). Can it work like this or am I missing something?

**Comment by wilsonodk** [comment]
Docker Compose shows examples of [variable substitution](https://docs.docker.com/compose/compose-file/#variable-substitution) for values that aren't Env Vars. I suppose you could use them for Env Vars.

**Comment by jritsema** [comment]
Seems like adding support for "env vars that are hidden in harbor" is related but separate from solving the "not checking in secrets" issue.  Wondering if we can just implement the former without addressing the latter right now (maybe solving it with something like [vault](https://github.com/hashicorp/vault)).  Thoughts?  

If we do this, some options to consider are:
- making everything in `hidden.yml` hidden in harbor
- add a shipment-level parameter that makes ALL env vars hidden
- support variable substitution

**Comment by jkurz** [comment]
Here is what I am proposing for this feature. It will give us the ability to have fine grain control over what is hidden, discover, or basic type. 

docker-compose

```
version: "2"
services:
  ict-erp:
    image: quay.io/turner/ict-erp:1.0.2-circle.11
    ports:
    - 80:56166
    environment:
      HEALTHCHECK: /ping
      PORT: "56166"
      HIDDEN: "foooooooo"
      USER_MANAGEMENT: "mss-user-management:prod"
```

harbor-compose

```
shipments:
  mss-argo-erp:
    env: dev
    barge: mss
    containers:
      - name: ict-erp
        variables:
          - HIDDEN:
              type: hidden
          - USER_MANAGEMENT:
              type: discover 
    replicas: 2
    group: ops
```

If there is a matching environment variable with the correlating environment variable name, then it gets associated with the type in harbor-compose. If not then we always default to basic. This allows us to use the .env files and still have hidden, basic or discover variables. 

@jc-money your request is valid, however I think it should be another option. I don't see how we can get away from having fine grained control over what type an environment variable is. 

FYI: my issue with just doing it in hidden.env is it's not very  intuitive. Also discover variables are a valid type and we should support them. This allows us to support any type of environment variable in the future, without having to use .env files as a hackaround.

**Comment by jritsema** [comment]
I like that idea.  

So in your example above, you could remove `HIDDEN: fooooo` from docker-compose.yml and add it to a ".gitignored" hidden.env.

Or a syntax-variant on that idea (less verbose)...

```
shipments:
  mss-argo-erp:
    env: dev
    barge: mss
    containers:
      - name: ict-erp
        hidden_variables:
        - HIDDEN
        - ANOTHER_HIDDEN
        discover_variables:
        - USER_MANAGEMENT
        - ANOTHER_DISCOVER
    replicas: 2
    group: ops
```

Or another option we could consider is using labels like we've talked about for [harbor port configuration](https://github.com/turnerlabs/harbor-compose/issues/30)?

```
version: "2"
services:
  ict-erp:
    image: quay.io/turner/ict-erp:1.0.2-circle.11
    ports:
    - 80:56166
    environment:
      HEALTHCHECK: /ping
      PORT: "56166"
      HIDDEN: "foooooooo"
      USER_MANAGEMENT: "mss-user-management:prod"
    labels:
    - harbor.envvars.HIDDEN: hidden
    - harbor.envvars.USER_MANAGEMENT: discover
```

**Comment by jkurz** [comment]
and yet again, I think the labels approach is going to be the winner for me. Especially if we decide to do Ports this way.

We could do ports either way. Whichever one we choose though, we should use for both use cases. 

Right now I am leaning towards the labels approach. Only downside I could see with it, is if we continue to use it for everything, then it could get out of control pretty quickly.

**Comment by wilsonodk** [comment]
I may just be missing something, but it appears that you're checking hidden values into source control. That definitely defeats the purpose.

FWIW, I really like the label variant:

``` yml
version: "2"
services:
  ict-erp:
    image: quay.io/turner/ict-erp:1.0.2-circle.11
    ports:
    - 80:56166
    environment:
      HEALTHCHECK: /ping
      PORT: "56166"
      PASSWORD: "${USER_PASSWORD}"
      USER_MANAGEMENT: "mss-user-management:prod"
    labels:
    - harbor.envvars.PASSWORD: hidden
    - harbor.envvars.USER_MANAGEMENT: discover
```

**Comment by jritsema** [comment]
No @wilsonodk, sorry typo, that's what I was trying to clarify.  So you could either add a `.env`...

```
cat .env
PASSWORD=foo
```

with this docker-compose.yml (like yours above)...

``` yaml
version: "2"
services:
  ict-erp:
    image: quay.io/turner/ict-erp:1.0.2-circle.11
    ports:
    - 80:56166
    environment:
      HEALTHCHECK: /ping
      PORT: "56166"
      USER_MANAGEMENT: "mss-user-management:prod"
      PASSWORD: "${PASSWORD}"
```

Or put the secrets in a `hidden.env` file and have a docker-compose.yml that looked like...

``` yaml
version: "2"
services:
  ict-erp:
    image: quay.io/turner/ict-erp:1.0.2-circle.11
    ports:
    - 80:56166
    environment:
      HEALTHCHECK: /ping
      PORT: "56166"
      USER_MANAGEMENT: "mss-user-management:prod"
    env_file: hidden.env
```

...or, use the first docker-compose.yml without .env by passing them via the shell.
