### ISSUE TITLE
Support for advanced port configuration and multiple ports

### ISSUE THREAD

**Issue by jritsema** [turnerlabs/harbor-compose#30]
proposed design:

```
shipments:
  shipment1:
    env: dev
    barge: corp-sandbox
    replicas: 2
    containers:
    - container1
      ports:
      - name: PORT
        value: 34567
        protocol: http
        public_port: 80
        health_check: "/_hc"
        external: true
        primary: true
        public_vip: false
        enable_proxy_protocol: false
        ssl_type: arn|iam
        ssl_arn: ''
```

**Comment by jritsema** [comment]
Or another approach we could consider would be to use [labels](https://docs.docker.com/compose/compose-file/#/labels) so that the configuration would stay in the docker-compose.yml file.

For example...

```
version: "2"
services:
  web-app:
    image: registry.services.dmtio.net/my-web-app:1.0.0
    ports:
    - "80:5000"
    - "443:6000"
    environment:
      PORT: 5000
      NODE_ENV: production
    labels:
      harbor.port.80.protocol: http
      harbor.port.80.healthcheck: /hc
      harbor.port.80.enable_proxy_protocol: true
      harbor.port.443.protocol: https
      harbor.port.443.healthcheck: /hc
      harbor.port.443.ssl_type: arn
      harbor.port.443.ssl_arn: xxxx
```
