### ISSUE TITLE
Work better with continuous delivery

### ISSUE THREAD

**Issue by jritsema** [turnerlabs/harbor-compose#34]
I'd like to make Harbor Compose work better for teams that are using a CD process.  In these scenarios, the image version in `docker-compose.yml` is not automatically updated with each commit and therefore is not the source of truth for a particular environment.  Running `harbor-compose up` would then deploy an older version.  

Here are a few options to address this...

1)  Make `harbor-compose up` default to not touching the image and instead add a new flag, e.g.,  `harbor-compose up -i` to do it.

2)  Add a new configuration option in `harbor-compose.yml` that controls the behavior.  For example, this would cause `harbor-compose up` to deploy the image version in docker-compose.yml:

```
shipments:
  my-web-app:    
    env: dev
    useImageVersion: true
```

or maybe this if the majority of folks aren't using CD...

```
shipments:
  my-web-app:    
    env: dev
    ignoreImageVersion: true
```

I think I prefer option 2 since it's a one-time setting, and you don't have to think about CLI args every time you use the tool.  Thoughts?
