### ISSUE TITLE
Implement deploy command for CI/CD

### ISSUE THREAD

**Issue by jritsema** [turnerlabs/harbor-compose#73]
The `deploy` command should deploy all containers in all shipments defined by compose files. This command is a subset of the up command without support for uploading environment variables or making any other shipment modifications. It's useful for making CI/CD pipelines even easier.

For example, given the following `harbor-compose.yml` ...

```
version: "1"
shipments:
  shipment1:
    env: dev
    containers:
      - container1
      - container2
  shipment2:
    env: dev
    containers:
      - container3
      - container4 
```

and the following env vars defined in your build... 

```
SHIPMENT1_DEV_TOKEN
SHIPMENT2_DEV_TOKEN
```

you could deploy the shipments from CircleCI using:

```
harbor-compose deploy
```

and if you wanted to also deploy the shipments to QA, you could add the following env vars and then do:

```
SHIPMENT1_QA_TOKEN
SHIPMENT2_QA_TOKEN
```
```
harbor-compose deploy --env qa
```

...all with a single harbor-compose.yml.  And your CI/CD build scripts would be nice and clean...

- set image versions (either as env vars or defined in docker-compose.yml)
- docker-compose build
- docker-compose up -d && ./test
- docker-compose push
- harbor-compose deploy

...and all of your container images would be built, tested, pushed to a registry, cataloged and deployed.
