### ISSUE TITLE
Update catalog command to use customs for CI/CD

### ISSUE THREAD

**Issue by jritsema** [turnerlabs/harbor-compose#74]
The `catalog` command should catalog all containers in all shipments defined by compose files.

For example, given the following `harbor-compose.yml` ...

```
version: "1"
shipments:
  shipment1:
    env: dev
    containers:
      - container1
      - container2
  shipment2:
    env: dev
    containers:
      - container3
      - container4 
```

and the following env vars defined in your build... 

```
SHIPMENT1_DEV_TOKEN
SHIPMENT2_DEV_TOKEN
```

you could catalog the shipment images from CircleCI using:

```
harbor-compose catalog
```

...all with a single harbor-compose.yml.  And your CI/CD build scripts would be nice and clean...

- set image versions (either as env vars or defined in docker-compose.yml)
- docker-compose build
- docker-compose up -d && ./test
- docker-compose push
- harbor-compose catalog

...and all of your container images would be built, tested, pushed to a registry, and cataloged.
