### ISSUE TITLE
Environment variables containing equals signs ("=") are not parsed correctly

### ISSUE THREAD

**Issue by jritsema** [turnerlabs/harbor-compose#77]
This is an issue with the [underlying libcompose library](https://github.com/docker/libcompose/issues/454) that is used to parse the docker-compose.yml file.

For example:
```
version: "2"
services:
  container:
    image: helloworld
    environment:
      CHAR_EQUAL: foo=bar
```
