### ISSUE TITLE
Add healthcheck_timeout to harbor-compose.yml

### ISSUE THREAD

**Issue by jritsema** [turnerlabs/harbor-compose#78]
Support for healthcheck_timeout in harbor-compose which includes:

- `up` command updating value if it's specified in harbor-compose.yml
- `generate` command writing current value to harbor-compose.yml
- `init` command prompting for value

```
version: "1"
shipments:
  my-web-app:
    env: dev
    barge: digital-sandbox
    enableMonitoring: false
    healthcheckTimeoutSeconds: 10
```
