### ISSUE TITLE
Add enableMonitoring to harbor-compose.yml

### ISSUE THREAD

**Issue by jritsema** [turnerlabs/harbor-compose#79]
New property in `harbor-compose.yml`

```
version: "1"
shipments:
  my-web-app:
    env: dev
    barge: digital-sandbox
    enableMonitoring: false
    containers:
      - web-app    
    replicas: 2
    group: mss
    property: turner
    project: turner
    product: turner
```
