### ISSUE TITLE
Support use of variable substitution in docker-compose.yml for things other than envvars

### ISSUE THREAD

**Issue by jritsema** [turnerlabs/harbor-compose#82]
[Variable substitution](https://docs.docker.com/compose/compose-file/compose-file-v2/#variable-substitution) is currently only supported for [envvars](https://docs.docker.com/compose/environment-variables/).

```yaml
environment:
  RACK_ENV: development
  SHOW: "true"
  DB_PASSWORD: ${DB_PASSWORD}
```

This would add support for other things (currently [`image`](https://github.com/turnerlabs/harbor-compose/blob/master/compose-reference.md#image) and [`ports`](https://github.com/turnerlabs/harbor-compose/blob/master/compose-reference.md#ports)).

```yaml
web:
  image: "webapp:${TAG}"
```
