### ISSUE TITLE
The generate command should write env vars to an env file

### ISSUE THREAD

**Issue by jritsema** [turnerlabs/harbor-compose#85]
In order to discourage folks from checking sensitive environment variables in to source control, the `generate` command should write to an `.env` file and then reference those vars in `docker-compose.yml`.  We could also automatically add/append .env to .gitignore...

#### .env
```bash
AWS_ACCESS_KEY_ID=xxxx
```

#### docker-compose.yml
```yaml
version: "2"
services:
  app:
    image: quay.io/turner/app:1.0
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
```

#### .gitignore
```bash
node_modules
.env
```

**Comment by jritsema** [comment]
After reading the [docker](https://docs.docker.com/compose/compose-file/compose-file-v2/#variable-substitution) [docs](https://docs.docker.com/compose/env-file/) more closely, the `.env` file seems to be primarily intended for "default values for environment variables" used in variable substitution .  According to the docs...

> The environment variables you define here will be used for variable substitution in your Compose file

That said, I'm thinking we do this instead...

#### harbor.env
```bash
AWS_ACCESS_KEY_ID=xxxx
FOO=bar
```

#### docker-compose.yml
```yaml
version: "2"
services:
  app:
    image: quay.io/turner/app:1.0
    env_file: 
    - harbor.env
```

#### .gitignore
```bash
node_modules
harbor.env
```
Thoughts?
